service: iopipe-go-acceptance-test-serverless

provider:
  name: aws
  runtime: go1.x
  stage: master
  region: us-west-2
  role: ${env:IAM_ROLE}
  environment:
    IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  api-gateway:
    events:
      - http:
          path: /
          method: get
    handler: bin/api-gateway
  api-trigger:
    environment:
      API_GATEWAY_URL: ${env:API_GATEWAY_URL}
    events:
      - schedule: rate(10 minutes)
    handler: bin/api-trigger
  baseline:
    events:
      - schedule: rate(10 minutes)
    handler: bin/baseline
  baseline-coldstart:
    events:
      - schedule: rate(10 minutes)
    handler: bin/baseline-coldstart
  coldstart:
    events:
      - schedule: rate(10 minutes)
    handler: bin/coldstart
  error:
    events:
      - schedule: rate(10 minutes)
    handler: bin/error
  event:
    events:
      - schedule: rate(10 minutes)
    handler: bin/event
  handled-error:
    events:
      - schedule: rate(10 minutes)
    handler: bin/handled-error
  labels:
    events:
      - schedule: rate(10 minutes)
    handler: bin/labels
  metrics:
    events:
      - schedule: rate(10 minutes)
    handler: bin/metrics
  panic:
    events:
      - schedule: rate(10 minutes)
    handler: bin/panic
  success:
    events:
      - schedule: rate(10 minutes)
    handler: bin/success
  timeout:
    events:
      - schedule: rate(10 minutes)
    handler: bin/timeout
    timeout: 1
